### ISSUE TITLE
Feature 1: User can search for anime

### ISSUE THREAD

**Issue by aaronsoukaphay** [aaronsoukaphay/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for anime by title name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User enters the title of an anime in search box and they are taken to a page that shows a list of all animes that match the keywords written in the search box.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="970" alt="Screenshot 2023-08-13 at 4 33 53 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/b2b10b1a-5b98-417f-93a0-de122217dc29">
<img width="821" alt="Screenshot 2023-08-13 at 4 34 02 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/40daad0f-0d17-4818-aad6-5a1a6fdbf50b">
<img width="818" alt="Screenshot 2023-08-13 at 4 34 10 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/7a188582-843a-4a4d-84ac-08bb2353e7e8">
<img width="820" alt="Screenshot 2023-08-13 at 4 34 17 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/6d238a7c-b0cf-4671-9087-998b6a49b6db">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 
- [x] Create the HTML for the header in the header-container so that it matches the figma example.
- [x] Create a carousel that cycles between 5 different images every 3 seconds
- [x] Create the HTML for the search box in the search-container so that it matches the figma example
- [x] Create a new function named viewSwap with a single parameter representing the name of the view to show (the values will be "home", ”search-results”, ”details”, "watchlist", "edit-watchlist", or "most-popular"). This function should show the view whose name was provided as an argument, as well as assign the string argument to the data.view property so that the currently shown view is tracked in the data model for the application.
- [x] Add an empty unordered list to the div[data-view="search-results"] element in the HTML.
- [x]  Create some dummy journal entries to the unordered list in the HTML and style them to match the example entries in the figma. Each entry’s content should be in a single li element within the ul element.
- [x]  Check that the example entries you just created in the unordered list are responsive for both mobile and desktop screens.
- [x] Define a function named renderEntry with a single parameter named entry. This parameter represents a single object for a single entry from the data.entries. The function should generate and return a DOM tree for a single entry that matches the entries you created in the unordered list.
- [x] Create a function named toggleNoEntries which toggles the no entries text to show or hide when the function is called.
- [x] Add a 'submit' event listener to the form element that:
   - [x] prevents the page from refreshing when the form is submitted.
   - [x] builds a URL that searches a specific anime based on the input
   - [x] uses viewSwap to show the "search-results" view
   - [x] Render a DOM tree for the newly submitted entry object using the renderEntry function.
   - [x] Prepends the new DOM tree to the unordered list.
   - [x] conditionally uses the toggleNoEntries function as needed to remove the no entries text.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
