### ISSUE TITLE
Feature 2: User can view most popular animes and top upcoming animes

### ISSUE THREAD

**Issue by aaronsoukaphay** [aaronsoukaphay/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view most popular animes currently airing and can instantly see most popular upcoming animes on the home page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User selects the top animes tab in the header and is taken to a page that lists the most popular animes currently airing. Whenever user is on the home page they can view the top upcoming animes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="280" alt="Screenshot 2023-08-13 at 7 49 05 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/4bf71608-cf82-4e50-ab5a-63edb725cadc">
<img width="789" alt="Screenshot 2023-08-13 at 7 49 17 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/49185ec1-2942-4d18-9cf5-eaa9631e9ff8">
![Screenshot 2023-08-15 at 2 16 57 PM](https://github.com/aaronsoukaphay/ajax-project/assets/132744086/fd5f1fa2-e1d6-457d-903d-24cca166cae6)
![Screenshot 2023-08-15 at 2 17 05 PM](https://github.com/aaronsoukaphay/ajax-project/assets/132744086/5efce1ae-1e51-4c13-98b1-bf6a2d07716b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Define a function named topAnimes that:
   - [x] Utilizes XMLHttpRequest to make an API request for the top rated anime
   - [x] Loops over the response and create a DOM tree for each entry
   - [x] Append each entry to the DOM
- [x] Define a function named newlyReleasedAnime that 
   - [x] Utilizes XMLHttpRequest to make an API request for top upcoming anime
   - [x] Loop over the response and create a DOM tree for each entry
   - [x] Append each entry to the DOM
- [x] Make sure page stays on the same page when it is refreshed.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
