### ISSUE TITLE
Feature 3: User can view anime details

### ISSUE THREAD

**Issue by aaronsoukaphay** [aaronsoukaphay/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view anime details

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User selects an anime listing and is taken to a page that provides information such as: synopsis, year release, score, genres, and a trailer for the anime

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="259" alt="Screenshot 2023-08-13 at 7 54 07 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/763d8e00-731f-4c88-8b1d-6b3617945c11">
<img width="788" alt="Screenshot 2023-08-13 at 7 54 16 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/2da06199-5a73-4adb-92ea-0bb373d869aa">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for the details page
- [x] Add an event listener to the ul in the search-results view which does the following when a result is clicked:
   - [x] Use the viewSwap function to show the details page.
   - [x] Find the result object in the **data.searchResults** array whose id matches the data-entry-id attribute value of the clicked entry and assigns that entry’s object to the **data.selected** property.
   - [x] Displays the synopsis, year released, score, and genre information from the API request
   - [x] Include trailer of the selected anime
- [x] Create an anchor button called "Add to watchlist"
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
