### ISSUE TITLE
Feature 4: User can add animes to watchlist

### ISSUE THREAD

**Issue by aaronsoukaphay** [aaronsoukaphay/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add anime to watchlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user adds an anime to their watchlist via anime details page, they are taken to a collection of all the animes they have added to their watchlist

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="626" alt="Screenshot 2023-08-13 at 7 57 30 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/aca6b7ae-ddea-4d0a-8c86-51a88c8f699e">
<img width="796" alt="Screenshot 2023-08-13 at 7 57 40 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/6ec637eb-4fc1-492b-ba43-7716cca3b041">
<img width="789" alt="Screenshot 2023-08-13 at 7 57 46 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/e3546dea-a65f-4ab8-8d0f-661d6d3b8e58">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Fix bug that allows user to click on title of anime which takes them to an empty details page.
- [x] Update handleDOMContentLoaded function to load Top Animes and Top Upcoming when data.view is watchlist.
- [x] Add an event listener to add to watchlist button that:
   - [x] viewSwaps to watchlist
   - [x] stores selected anime into data.watchlist.
- [x] Create a toggleNoWatchlistEntries function to show a message when there is nothing in the watchlist.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
