### ISSUE TITLE
Feature 5: User can delete anime from watchlist

### ISSUE THREAD

**Issue by aaronsoukaphay** [aaronsoukaphay/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete anime from watchlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user selects a listing on the watchlist page and removes that anime from the watchlist, it is removed from the watchlist page. A modal will popup confirming the removal of the anime from the watchlist. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="605" alt="Screenshot 2023-08-13 at 8 00 40 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/fd5469a6-7761-458a-9814-0c4242509b37">
<img width="785" alt="Screenshot 2023-08-13 at 8 00 46 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/6e51e44f-1dc6-41c2-ac2b-7b4a76f03f94">
<img width="780" alt="Screenshot 2023-08-13 at 8 00 53 PM" src="https://github.com/aaronsoukaphay/ajax-project/assets/132744086/e7edcf07-a2e1-4661-b334-bc5f395d5fc2">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] If data.view is 'watchlist':
   - [x] Update title from details to edit watchlist
   - [x] Hide Add to watchlist and add remove from watchlist button in its place
- [x] Add an event listener to remove from watchlist button that:
   - [x] Show a confirmation modal when the user clicks 'remove from watchlist' button
- [x] When the user clicks cancel, hide the modal
- [x] When the user clicks confirm: 
   - [x] remove the corresponding anime from the data model's watchlist array
   - [x] remove the entry's li element from the DOM
   - [x] conditionally uses the toggleNoEntries function to show the no entries text if needed
   - [x] hide the modal
   - [x] swap to the watchlist view 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
